Traceback (most recent call last):
  File "C:\Users\iuriol\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\iuriol\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iuriol\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iuriol\AppData\Local\Programs\Python\Python312-32\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\iuriol\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\iuriol\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\iuriol\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from matplotlib import pyplot as plt 
import numpy as np

h = 6.62607015e-34 
c = 2.99792458e+8
k = 1.380649e-23 
pi = np.pi

warnings.filterwarnings('ignore')


def planck(wav, T):
    a = 2.0*pi*h*c**2
    b = h*c/(wav*k*T)
    intensity = a/((wav**5)*(np.exp(b)-1.0))
    return intensity

wavelengths = np.arange(1e-9, 3e-6, 1e-9)

temperatures = [5500, 5000, 4500, 4000, 3500]

for T in temperatures:
    intensity = planck(wavelengths, T)
    plt.plot(wavelengths*1e9, intensity*1e-12, label=f"T={T}K")

plt.xlabel("Wavelength (nm)")
plt.ylabel("Intensity (kJ/nm)")
plt.title("Planck's Law")
plt.legend()
plt.show()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[1], line 9[0m
[0;32m      6[0m k [38;5;241m=[39m [38;5;241m1.380649e-23[39m 
[0;32m      7[0m pi [38;5;241m=[39m np[38;5;241m.[39mpi
[1;32m----> 9[0m [43mwarnings[49m[38;5;241m.[39mfilterwarnings([38;5;124m'[39m[38;5;124mignore[39m[38;5;124m'[39m)
[0;32m     12[0m [38;5;28;01mdef[39;00m [38;5;21mplanck[39m(wav, T):
[0;32m     13[0m     a [38;5;241m=[39m [38;5;241m2.0[39m[38;5;241m*[39mpi[38;5;241m*[39mh[38;5;241m*[39mc[38;5;241m*[39m[38;5;241m*[39m[38;5;241m2[39m

[1;31mNameError[0m: name 'warnings' is not defined

